### ISSUE TITLE
Group conditional evaluator

### ISSUE THREAD

**Issue by kke** [kontena/opto#14]
Something like:
```yaml
foo:
  type: integer
  value: 1
bar:
  type: boolean
  value: true
```

```ruby
  group.true?(
    foo: 1
    bar: true
  )
  => true
```

Practically just move the conditional handling so that it can be neatly used from the outside.
