### ISSUE TITLE
Allow grouping type validations and transforms under separate keys

### ISSUE THREAD

**Issue by kke** [kontena/opto#34]
Something like:

```yaml
username:
  type: string
  validate:
     min_length: 10
  transform:
     - upcase # maybe allow array like this  instead of "upcase: true"
     - strip
  from:
     env: FOO
```

**Comment by jakolehm** [comment]
Does this mean that `type` can have 3 different config things: `validate`, `transform` and `options` ?

**Comment by kke** [comment]
Yes.

`options` is for declaring choices for enums, which is a bit misleading key.

**Comment by jakolehm** [comment]
IMHO if we are going to change this structure we should think it so that we have well defined top-level keys for type options. Which means that `options` cannot be just `enum` specific thing.

**Comment by kke** [comment]
We could drop the whole enum type.

```yaml
food:
  type: string
  validate:
    in:
      - Pizza
      - Burger
  from:
    prompt: Select lunch
```
