### ISSUE TITLE
Importing from other files

### ISSUE THREAD

**Issue by kke** [kontena/opto#39]
This could be something like:

## A: YAML-resolver

```yaml
foo:
  type: string
  from:
    yaml:
      path: foo.yml
      key: foo
```

## B: YAML-resolver and "hash" type

```yaml
variables:
  foo:
    type: hash
    from:
      yaml: foo.yml

services:
  dog:
     environment:
       - "FOO=${foo[bar]}"
```

## C: Subgroups and YAML-resolver

```yaml
variables:
  foo:
    type: group
    from:
      yaml: foo.yml

services:
  dog:
     environment:
       - "FOO=${foo.bar}"
```

Looks like all variations include a YAML-resolver. All variations can probably coexist nicely so maybe no choice is necessary.

### Filename interpolation

The yaml filename should probably be interpolatable, and to not break kontena YAML reader, it should probably go something like:

```yaml
  from:
    yaml:
      path: 
        interpolate: ${foofile}
      key: foo
```

(kontena-cli interpolator skips any lines that start with `/\s+interpolate:` because opto interpolates those lines on its own)
