### ISSUE TITLE
Implement some kind of conditional grouping.

### ISSUE THREAD

**Issue by kke** [kontena/opto#4]
Instead of:

```yaml
  use_bundled_mysql:
    type: boolean
    default: true
    from:
      prompt: Use bundled mysql?
  bundled_mysql_host:
    only_if: use_bundled_mysql
    type: string
    value: mysql
    to: mysql_host
  bundled_mysql_user:
    only_if: use_bundled_mysql
    type: string
    value: wordpress
    to: mysql_user
```

Something like:

```yaml
  use_bundled_mysql:
    type: boolean
    default: true
    from:
      prompt: Use bundled mysql?
    if:
      true:
        mysql_host:
          type: string
          value: mysql
        mysql_user:
          type: string
          value: wordpress
      false:
        mysql_host:
          type: string
          from:
            prompt: Enter MySQL hostname
        mysql_user:
          type: string
          from:
            prompt: Enter MySQL username
```
